### PR TITLE
Add "declname" in parameter parser.

### PR DESCRIPTION
**Pull request by wenjie1991**
Commits fix the error when using latest Rakudo https://github.com/raku-community-modules/Raku-Parser/issues/1

### CODE REVIEW

**Comment by wenjie1991** [comment]
This addresses the issue caused by a change of the Rakudo rakudo/rakudo@ca78390, which causes an error when handling subroutine parameters.

**Comment by lizmat** [comment]
Would you be interested in taking over maintenance of this module completely?

**Comment by wenjie1991** [comment]
> Would you be interested in taking over maintenance of this module completely?

Though I am not competent to develop it, I am glad to keep it functional until someone appears.

**Comment by lizmat** [comment]
Then I will merge this PR, as you appear to know more about it than I do  :-)

**Comment by lizmat** [comment]
Thank you!

**Comment by wenjie1991** [comment]
Thanks :-)

**Pull request merged**
